id: D04DEF538
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-18T11:11:25+00:00'
last_modified: '2022-05-30T06:43:03.230805+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    e999:
      image_group_id: I1PD95965
      title: དབང་ཕྱུག་བྱེད་པ་པོ་ཉིད་སེལ་བ་དང་ཁྱབ་འཇུག་བྱེད་པ་པོ་གཅིག་ཉིད་སེལ་བར་བྱེད་པ།
      total_pages: 1865
      order: 120
      base_file: e999.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
